import 'package:quizygo/core/uitls/app_assets.dart';

abstract class PartnerData {
  static const Map<String, List<String>> quetionsAndAnswersEn = {
    "1": [
      "What kind of restaurants do you prefer?",
      "Fancy",
      "Fast Casual",
      "Food Truck",
      "Cafe",
    ],
    "2": [
      "What makes you most afraid?",
      "Clowns",
      "Dark",
      "loneliness",
      "High places",
    ],
    "3": [
      "your favorite style",
      "Classic",
      "Casual",
      "Sporty",
      "Bohemian",
    ],
    "4": [
      "you like most",
      "Food",
      "Cars",
      "Money",
      "Traveling",
    ],
    "5": [
      "you prefer",
      "Meat",
      "Chicken",
      "Seafood",
      "Vegetables",
    ],
    "6": [
      "you like to watch",
      "Sunset",
      "Sunrise",
      "Stars",
      "Aurora",
    ],
    "7": [
      "What do you like most",
      "Dogs",
      "Cats",
      "Hamster",
      "Turtle",
    ],
    "8": [
      "What do you do in your free time",
      "Sleep",
      "Playing",
      "Reading",
      "Meditation",
    ],
    "9": [
      "you like to practice",
      "Swimming",
      "Football",
      "Basketball",
      "Boxing",
    ],
    "10": [
      "you are more interested in news about",
      "Art",
      "Sports",
      "Politics",
      "Fashion"
    ],
    "11": [
      "your favorite color",
      "Black",
      "Blue",
      "Pink",
      "White",
    ],
    "12": [
      "you wish to travel to ",
      "Bail",
      "Maldives",
      "Kenya",
      "Dubai",
    ],
    "13": [
      "What is the first thing you do in the morning?",
      "Work",
      "Gym",
      "Studying",
      "Stay at Home",
    ],
    "14": [
      "your favorite type of chocolate",
      "Dark",
      "White",
      "Milk",
      "Nuts",
    ],
    "15": [
      "your favorite season",
      "Winter",
      "Autumn",
      "Spring",
      "Summer",
    ],
  };
  static const Map<String, List<String>> quetionsAndAnswersAr = {
    "1": [
      "أي نوع من المطاعم تفضل؟",
      "الفاخرة",
      "السريعه",
      "عربات الطعام",
      "كافيه",
    ],
    "2": [
      "ماالذي يجعلك خائفا أكثر",
      "المهرجين",
      "الظلام",
      "الوحدة",
      "الأماكن المرتفعة",
    ],
    "3": [
      "ذوقك المفضل",
      "كلاسيكي",
      "غير رسمي",
      "رياضي",
      "بوهيمي",
    ],
    "4": [
      "تحب اكثر",
      "الطعام",
      "السيارات",
      "المال",
      "السفر",
    ],
    "5": [
      "انت تفضل",
      "اللحوم",
      "الدواجن",
      "المأكولات البحرية",
      "الخضروات",
    ],
    "6": [
      "تحب أن تشاهد",
      "الغروب",
      "الشروق",
      "النجوم",
      "الشفق القطبي",
    ],
    "7": [
      "ماذا تحب أكثر",
      "الكلاب",
      "القطط",
      "الهامستر",
      "السلاحف",
    ],
    "8": [
      "ماذا تفعل في وقت فراغك؟",
      "تنام",
      "تلعب",
      "تقرأ",
      "تتأمل",
    ],
    "9": [
      "تحب أن تتدرب",
      "سباحة ",
      "كرة قدم",
      "كرة سلة",
      "ملاكمة",
    ],
    "10": [
      "انت مهتم أكثر بأخبار",
      "الفن",
      "الرياضة",
      "السياسة",
      "الموضة",
    ],
    "11": [
      "لونك المفضل",
      "الأسود",
      "الأزرق",
      "الوردي",
      "الأبيض",
    ],
    "12": [
      "التي ترغب في السفر إليها",
      "بالي",
      "مالديفز",
      "كينيا",
      "دبي",
    ],
    "13": [
      "ما هو أول شيء تفعله في الصباح؟",
      "العمل",
      "الچيم",
      "الدراسة",
      "البقاء في المنزل",
    ],
    "14": [
      "نوع الشوكولاتة المفضل لديك",
      "الداكنه",
      "البيضاء",
      "الحليب",
      "المكسرات",
    ],
    "15": [
      "الموسم المفضل لك",
      "الشتاء",
      "الخريف",
      "الربيع",
      "الصيف",
    ],
  };
  static const Map<String, List<String>> quetionsAr = {
    "1": [
      "أي نوع من المطاعم تفضل/يفضل 1؟",
      "الفاخرة",
      "السريعه",
      "عربات الطعام",
      "كافيه",
    ],
    "2": [
      "ماالذي يجعل 1 خائفا/خائفة أكثر",
      "المهرجين",
      "الظلام",
      "الوحدة",
      "الأماكن المرتفعة",
    ],
    "3": [
      "ذوق 1 المفضل",
      "كلاسيكي",
      "غير رسمي",
      "رياضي",
      "بوهيمي",
    ],
    "4": [
      "1 تحب/يحب اكثر",
      "الطعام",
      "السيارات",
      "المال",
      "السفر",
    ],
    "5": [
      "1 يفضل/تفضل",
      "اللحوم",
      "الدواجن",
      "المأكولات البحرية",
      "الخضروات",
    ],
    "6": [
      "تحب/يحب 1 أن تشاهد/يشاهد",
      "الغروب",
      "الشروق",
      "النجوم",
      "الشفق القطبي",
    ],
    "7": [
      "ماذا تحب/يحب 1 أكثر",
      "الكلاب",
      "القطط",
      "الهامستر",
      "السلاحف",
    ],
    "8": [
      "ماذا تفعل/يفعل 1 في وقت الفراغ؟",
      "تنام",
      "تلعب",
      "تقرأ",
      "تتأمل",
    ],
    "9": [
      "تحب/يحب 1 أن تتدرب/يتتدرب",
      "سباحة ",
      "كرة قدم",
      "كرة سلة",
      "ملاكمة",
    ],
    "10": [
      "1 مهتم/مهتمة أكثر بأخبار",
      "الفن",
      "الرياضة",
      "السياسة",
      "الموضة",
    ],
    "11": [
      "لون 1 المفضل",
      "الأسود",
      "الأزرق",
      "الوردي",
      "الأبيض",
    ],
    "12": [
      "1 ترغب/يرغب في السفر إليها",
      "بالي",
      "مالديفز",
      "كينيا",
      "دبي",
    ],
    "13": [
      "ما هو أول شيء تفعل/يفعل 1 في الصباح؟",
      "العمل",
      "الچيم",
      "الدراسة",
      "البقاء في المنزل",
    ],
    "14": [
      "نوع الشوكولاتة المفضل لدي 1",
      "الداكنه",
      "البيضاء",
      "الحليب",
      "المكسرات",
    ],
    "15": [
      "الموسم المفضل الي 1",
      "الشتاء",
      "الخريف",
      "الربيع",
      "الصيف",
    ],
  };

  static const Map<String, List<String>> images = {
    "1": [
      PartnerAssets.imagesPartnerFancy,
      PartnerAssets.imagesPartnerFastCasual,
      PartnerAssets.imagesPartnerFoodTruck,
      PartnerAssets.imagesPartnerCafe,
    ],
    "2": [
      FriendsAssets.imagesFriendsClowns,
      FriendsAssets.imagesFriendsDark,
      FriendsAssets.imagesFriendsLoneliness,
      FriendsAssets.imagesFriendsHighplaces
    ],
    "3": [
      PartnerAssets.imagesPartnerClassic,
      PartnerAssets.imagesPartnerCasual,
      PartnerAssets.imagesPartnerSport,
      PartnerAssets.imagesPartnerBohemian,
    ],
    "4": [
      PartnerAssets.imagesPartnerFood,
      PartnerAssets.imagesPartnerCars,
      PartnerAssets.imagesPartnerMoney,
      PartnerAssets.imagesPartnerTravelling,
    ],
    "5": [
      PartnerAssets.imagesPartnerMeat,
      PartnerAssets.imagesPartnerChicken,
      PartnerAssets.imagesPartnerSeafood,
      PartnerAssets.imagesPartnerVegetables,
    ],
    "6": [
      PartnerAssets.imagesPartnerSunset,
      PartnerAssets.imagesPartnerSunrise,
      PartnerAssets.imagesPartnerStars,
      PartnerAssets.imagesPartnerAurora,
    ],
    "7": [
      PartnerAssets.imagesPartnerDog,
      PartnerAssets.imagesPartnerCat,
      PartnerAssets.imagesPartnerHamster,
      PartnerAssets.imagesPartnerTurtle,
    ],
    "8": [
      PartnerAssets.imagesPartnerSleeping,
      PartnerAssets.imagesPartnerPlaying,
      PartnerAssets.imagesPartnerReading,
      PartnerAssets.imagesPartnerMeditation,
    ],
    "9": [
      PartnerAssets.imagesPartnerSwimming,
      PartnerAssets.imagesPartnerFootball,
      PartnerAssets.imagesPartnerBasketball,
      PartnerAssets.imagesPartnerBoxing,
    ],
    "10": [
      PartnerAssets.imagesPartnerArt,
      PartnerAssets.imagesPartnerSport,
      PartnerAssets.imagesPartnerPolitics,
      PartnerAssets.imagesPartnerFashion,
    ],
    "11": [
      PartnerAssets.imagesPartnerBlack,
      PartnerAssets.imagesPartnerBlue,
      PartnerAssets.imagesPartnerPink,
      PartnerAssets.imagesPartnerWhite,
    ],
    "12": [
      PartnerAssets.imagesPartnerBali,
      PartnerAssets.imagesPartnerMaldives,
      PartnerAssets.imagesPartnerKenya,
      PartnerAssets.imagesPartnerDubai,
    ],
    "13": [
      PartnerAssets.imagesPartnerWork,
      PartnerAssets.imagesPartnerGym,
      PartnerAssets.imagesPartnerStudying,
      PartnerAssets.imagesPartnerStayAtHome
    ],
    "14": [
      PartnerAssets.imagesPartnerDark,
      PartnerAssets.imagesPartnerWhiteChocolate,
      PartnerAssets.imagesPartnerMilk,
      PartnerAssets.imagesPartnerNuts,
    ],
    "15": [
      PartnerAssets.imagesPartnerWinter,
      PartnerAssets.imagesPartnerAutumn,
      PartnerAssets.imagesPartnerSpring,
      PartnerAssets.imagesPartnerSummer,
    ],
  };
}
