class Quetions {
  //{ QuetionId : [
  //Quetion,
  //awnser1,
  //awnser2,
  //awnser3,
  //awnser4,
  //]
  //}
  static const Map<String, List<String>> friendsQuetion = {
    "1": [
      "What experience do you want to have?",
      "Diving",
      "Sky Diving",
      "Camping",
      "Mountaineering"
    ],
    "2": [
      "Your favorite color",
      "Black",
      "Blue",
      "Pink",
      "White",
    ],
    "3": [
      "You wish to travel to ",
      "Bail",
      "Maldives",
      "Kenya",
      "Dubai",
    ],
    "4": [
      "You like to go out",
      "Single ",
      "With family",
      "With friends",
      "With new people"
    ],
    "5": [
      "What kind of snacks do you like most?",
      "PopCorn",
      "Nuts",
      "Candy",
      "Chips"
    ],
    "6": [
      "You like most",
      "Food",
      "Cars",
      "Money",
      "Traveling",
    ],
    "7": [
      "What is your morning drink?",
      "Tea",
      "Coffee",
      "Matcha",
      "Milk",
    ],
    "8": [
      "You prefer",
      "Meat",
      "Chicken",
      "Seafood",
      "Vegetables",
    ],
    "9": [
      "Your favorite season is",
      "Summer",
      "Winter",
      "Autum",
      "Spring",
    ],
    "10": [
      "What makes you most afraid?",
      "Clowns",
      "Dark",
      "loneliness",
      "High places",
    ],
    "11": [
      "Do you like to spend your weekend",
      "Watching TV",
      "Reading",
      "Sleeping",
      "trying something new",
    ],
    "12": [
      "The application you spend most of your time on",
      "Facebook",
      "Instagram",
      "Tik tok",
      "Snapchat",
    ],
    "13": [
      "You like to practice",
      "Swimming",
      "Football",
      "Basketball",
      "Boxing",
    ],
    "14": [
      "Your favorite ice cream flavour",
      "Vanilla",
      "Chocolate",
      "Mango",
      "Strawberry",
    ],
    "15": [
      "Your favorite style",
      "Classic",
      "Casual",
      "Sport",
      "Bohemian",
    ],
  };
  static const Map<String, List<String>> partnerQuetion = {
    "1": [
      "What kind of restaurants do you prefer?",
      "Fancy",
      "Fast Casual",
      "Food Truck",
      "Cafe",
    ],
    "2": [
      "The application you spend most of your time on",
      "Facebook",
      "Instagram",
      "Tik tok",
      "Snapchat",
    ],
    "3": [
      "Your favorite style",
      "Classic",
      "Casual",
      "Sporty",
      "Bohemian",
    ],
    "4": [
      "You like most",
      "Food",
      "Cars",
      "Money",
      "Traveling",
    ],
    "5": [
      "you prefer going out ",
      "alone",
      "with friends",
      "with Family",
      "with your lover",
    ],
    "6": [
      "You like to watch",
      "Sunset",
      "Sunrise",
      "Stars",
      "Aurora",
    ],
    "7": [
      "What Do you like most",
      "Dogs",
      "Cats",
      "Baghbhans",
      "Birds",
    ],
    "8": [
      "What do you do in your free time",
      "Sleep",
      "Watching a movie",
      "Reading",
      "Meditation",
    ],
    "9": [
      "You like to practice",
      "Swimming",
      "Football",
      "Basketball",
      "Boxing",
    ],
    "10": [
      "You are more interested in news about",
      "Art",
      "Sports",
      "Politics",
      "Fashion"
    ],
    "11": [
      "Your favorite color",
      "Black",
      "Blue",
      "Pink",
      "White",
    ],
    "12": [
      "You wish to travel to ",
      "Bail",
      "Maldives",
      "Kenya",
      "Dubai",
    ],
    "13": [
      "What is the first thing you do in the morning?",
      "Work",
      "Gym",
      "Jogging",
      "Stay at Home",
    ],
    "14": [
      "Your favorite type of chocolate",
      "Dark",
      "White",
      "Milk",
      "Nuts",
    ],
    "15": [
      "Your favorite season",
      "Winter",
      "Autumn",
      "Spring",
      "Summer",
    ],
  };
}
